### ISSUE TITLE
spexporter bash not command valid

### ISSUE THREAD

**Issue by johben** [ipHeaders/silverpeak-prometheus#23]
**Describe the bug**

**To Reproduce**
1. spexporter command

**Expected behavior**
test spexporter check

**Screenshots**

![image](https://user-images.githubusercontent.com/16960815/236893896-6e43d240-b012-4357-b9aa-87c0ef843b61.png)

**System (please complete the following information):**
 - Linux Version:  Linux (rocky 9.1)
 - Python Version 3.9.14

**Additional context**

Just trying to run step by step according to guide.

**Comment by ipHeaders** [comment]
Hey Johben, Will look into this one.

Can you run the following commands for us.

`which python3`

**Comment by ipHeaders** [comment]
Pending response. Closing in 5 days.
