### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by ibaarani** [ipHeaders/silverpeak-prometheus#3]
dude , need of grafana dashboard as well

**Comment by ipHeaders** [comment]
you mean create an example grafana dashboard? Thats something we are planning on working next, we just not there yet.

**Comment by badharan** [comment]
yeah , you are correct ,make it happen .

**Comment by ipHeaders** [comment]
We just created the Grafana dashboard on our labs. We will work on uploading it

**Comment by ipHeaders** [comment]
Dashboard has been uploaded to Grafana - https://grafana.com/grafana/dashboards/17745-silverpeak-exporter/
